### ISSUE TITLE
Bakers data.csv file not working

### ISSUE THREAD

**Issue by rinrinb** [jenrichmond/RLadiesSydney-blogdown#4]
Hello,

I'm would like to attempt Cleanitup5 challenge - converting bakers data from wide to long.
But I can't seem to find the link to download bakers data .CSV file.
Could you please advise? It seems to me the link is broken :)

Thank you so much! Your lessons are very useful and easy to follow for a new learner like me!

**Comment by jenrichmond** [comment]
you are welcome, ive fixed the link
Jenny

**Comment by rinrinb** [comment]
Thank you so much Jen for a quick response and for fixing it.
Could you please guide me on where to download the file? it still shows' fixing data links' for me.

Could you also fix the link for "frames data in wide format." please?

I hope you have a lovely day !
Fern

**Comment by jenrichmond** [comment]
hmmmm the frames link works fine for me....

**Comment by rinrinb** [comment]
Hello Jen,
I'm not sure where I should be downloading the file from. When I click the link, it took me to this page below: 

![Rladies - issue](https://user-images.githubusercontent.com/88297824/128440667-140b91b8-ba6e-4a30-a236-f17b5be7e6c8.JPG)

Thank you so much.
Fern

**Comment by jenrichmond** [comment]
ah yes, click on the raw button and then right link save as .csv

**Comment by rinrinb** [comment]
I got it now. Thanks so much Jen!
